{{- if .Values.tasks.enabled }}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "hdx-oss.fullname" . }}-check-alerts
  labels:
    {{- include "hdx-oss.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.tasks.checkAlerts.schedule | quote }}
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            {{- include "hdx-oss.selectorLabels" . | nindent 12 }}
            app.kubernetes.io/component: task
        spec:
          {{- if .Values.global.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml .Values.global.imagePullSecrets | nindent 12 }}
          {{- end }}
          restartPolicy: OnFailure
          containers:
            - name: task
              image: "{{ .Values.hyperdx.image.repository }}:{{ .Values.hyperdx.image.tag | default .Chart.AppVersion }}"
              imagePullPolicy: {{ .Values.hyperdx.image.pullPolicy }}
              command: ["node", "/app/packages/api/tasks/index", "check-alerts"]
              envFrom:
                - configMapRef:
                    name: {{ include "hdx-oss.fullname" . }}-app-config
              env:
                - name: NODE_ENV
                  value: "production"
                - name: OTEL_SERVICE_NAME
                  value: "hdx-oss-task-check-alerts"
                - name: APP_TYPE
                  value: "scheduled-task"
              resources:
                {{- toYaml .Values.tasks.checkAlerts.resources | nindent 16 }}
{{- end }}
